### ISSUE TITLE
Publish to GHCR

### ISSUE THREAD

**Issue by Malix-Labs** [playtron-os/playtron-os#149]
Hello Guys !

I am an enthusiast of Playtron and PlaytronOS

I would very much love that you publish PlaytronOS to [GitHub container registry (GHCR)](https://github.com/features/packages) : 

- https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images
- https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

**Comment by LukeShortCloud** [comment]
Hey @Malix-Labs , thanks for your interest in Playtron! We actually already do use the GitHub Container Registry for PlaytronOS. You can find our images here:

https://github.com/orgs/playtron-os/packages/container/package/playtron-os

The `0.18.0.66` tag is our Alpha 1 release.

Let me know if you have any troubles using that!

**Comment by Malix-Labs** [comment]
Ah, thanks !

It is not showing up in https://github.com/orgs/playtron-os/packages?repo_name=playtron-os though

**Comment by LukeShortCloud** [comment]
Agreed, we can add documentation about that. I'm not sure why the two links show different results. We'll link to the working one.

**Comment by Malix-Labs** [comment]
> I'm not sure why the two links show different results

I guess it is something to do with the github action file : 
https://github.com/playtron-os/playtron-os/blob/main/.github/workflows/container-build.yaml

**Comment by Malix-Labs** [comment]
@LukeShortCloud is it published in ghcr ?

**Comment by LukeShortCloud** [comment]
@Malix-Labs Yes! It always has been. I added some notes about it to the top of the developer section in our read me file here:

https://github.com/playtron-os/playtron-os?tab=readme-ov-file#linux-developer-tips

Hopefully that helps!

**Comment by Malix-Labs** [comment]
Nice to know, thanks

For some reasons, the GHCR packages doesn't show up as being built from this repository

**Comment by LukeShortCloud** [comment]
Yeah, I'm still not sure why it doesn't show up at the repository level. It's only at the organization level on GitHub. My first thought was maybe it was a difference of `playtron-os` vs `playtronos` as there are some minor inconsistencies of that usage throughout our various projects. However, that doesn't seem to be the case.

**Comment by LukeShortCloud** [comment]
I was finally able to fix the package link issue. A label was missing from the container images. As an alternative, I manually linked to the GitHub repository for Playtron GameOS to the GitHub package. This link now works: https://github.com/orgs/playtron-os/packages?repo_name=playtron-os
