### ISSUE TITLE
Broken link on official website

### ISSUE THREAD

**Issue by AarizYT** [playtron-os/playtron-os#155]
The link to this GitHub repository on the official website (https://www.playtron.one/playtron-os), under the "How will I be able to contribute to Playtron?" drop down menu, contains a trailing period which redirects to `https://github.com/playtron-os/playtron-os.` The correct URL is `https://github.com/playtron-os/playtron-os`

**Comment by LukeShortCloud** [comment]
Thank you @AarizYT  for reporting this! I've been trolled by this on websites in the past. Web browsers always think the period "." is part of the URL. I let our team know so it can be updated.
